### ISSUE TITLE
Error message when trying to scan through tasker.

### ISSUE THREAD

**Issue by bobbarebygg** [abhishekabhi789/GCS_for_Tasker#2]
16.05.06/LicenseCheckerTasker Checking cached only
16.05.06/LicenseCheckerTasker cache validity left -431365
16.05.06/LicenseCheckerTasker Cached status: Licensed
16.05.06/LicenseCheckerTasker Cached only: Licensed
16.05.06/E FIRE PLUGIN: Scan Action / com.twofortyfouram.locale.intent.action.FIRE_SETTING: 8 bundle keys
16.05.06/E Scan Action: plugin comp: com.abhi.gcsfortasker/com.joaomgcd.taskerpluginlibrary.action.IntentServiceAction
16.05.06/Ew add wait type Plugin3 time 60
16.05.06/Ew add wait type Plugin3 done
16.05.06/E handlePluginFinish: taskExeID: 3 result 3
16.05.06/E pending result code
16.05.06/E add wait task
16.05.06/E Error: 2
16.05.06/E Failed to scan code.

**Comment by abhishekabhi789** [comment]
Hi, thanks for the report. The error 'Failed to scan code' is more likely related to an issue with [Google Play Services](https://play.google.com/store/apps/details?id=com.google.android.gms&hl=en&gl=US)  which performs the scanning. The exact reason for the error is not clear, but it could be due to improper installation of scanner modules. You can try clearing the app data of Google Play Services or reinstalling updates from the Play Store to reset it.

**Comment by bobbarebygg** [comment]
It's funny actually cause I've read throught the troubleshooting guide and tried everything and last I tried uninstalling play services on google play thinking that I could easily install it again through google play 😅 Now I have a play services version from 2008 and google refusing to update it 🤦‍♂️ Oh well, should learn to read instructions better next time. 

edit: I was actually able to update it today for some reason, so now everything works as it should 😁👍

**Comment by abhishekabhi789** [comment]
Alright, glad to hear that issue is sorted out. I think simply clearing the app data for Google play service will solve the issue. Anyway I'll update the troubleshoot guide with this problem as well.
